name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download ncdu
        run: |
          wget https://dev.yorhel.nl/download/ncdu-2.9.1-linux-x86.tar.gz
          tar -xvf ncdu-2.9.1-linux-x86.tar.gz
          chmod +x ncdu
          echo "ncdu version:"
          sudo ./ncdu --version

      - name: Generate ncdu Disk Usage Report
        run: |
          echo "Starting disk scan..."
          sudo ./ncdu -0 -x --exclude-kernfs -t 4 -c -o disk-usage-before.json.zst /
          echo "Scan complete."
          ls -lh disk-usage-before.json.zst

      - name: Free Disk Space (Custom Script)
        shell: bash
        run: |
          sudo rm -rf /usr/lib/jvm
          sudo rm -rf /usr/lib/dotnet
          sudo rm -rf /usr/share/swift
          sudo rm -rf /usr/share/miniconda
          sudo rm -rf /usr/local/julia*
          sudo rm -rf /usr/local/aws-sam-cli
          sudo rm -rf /usr/local/aws-cli
          sudo rm -rf /usr/local/graalvm
          sudo rm -rf /usr/local/share/powershell
          sudo rm -rf /usr/local/share/chromium
          sudo rm -rf /usr/local/lib/node_modules
          sudo rm -rf /opt/microsoft
          sudo rm -rf /opt/hostedtoolcache/go
          sudo rm -rf /opt/hostedtoolcache/Ruby
          sudo rm -rf /opt/hostedtoolcache/CodeQL

      - name: Free Disk Space
        uses: BRAINSia/free-disk-space@v2
        with:
          tool-cache: false
          mandb: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: false

      - name: Generate ncdu Disk Usage Report
        run: |
          echo "Starting disk scan..."
          sudo ./ncdu -0 -x --exclude-kernfs -t 4 -c -o disk-usage-after.json.zst /
          echo "Scan complete."
          ls -lh disk-usage-after.json.zst

      - name: Compress Reports
        run: |
          echo "ZSTD version:"
          zstd --version
          echo "Packaging reports..."
          /usr/bin/tar -I "zstd -19 -T0" -cvf ncdu-report.tar.zst disk-usage-before.json.zst disk-usage-after.json.zst
          echo "Package created:"
          ls -lh ncdu-report.tar.zst

      - name: Upload Disk Usage Report
        uses: actions/upload-artifact@v6
        with:
          name: ncdu-report
          retention-days: 5
          path: ncdu-report.tar.zst
